"use client";

import Link from "next/link";
import { formatPeso } from "./catalog";
import { ProductImage } from "./product-image";
import { site } from "./site-data";
import { useStore } from "./store-provider";

export function CartView() {
  const { cart, publicProducts, updateQuantity, removeFromCart } = useStore();
  const lines = cart.map((line) => ({ ...line, product: publicProducts.find((product) => product.slug === line.slug) })).filter((line) => line.product);
  const total = lines.reduce((sum, line) => sum + (line.product?.price ?? 0) * line.quantity, 0);
  const summary = lines.map((line) => `${line.quantity} × ${line.product?.name} — ${formatPeso((line.product?.price ?? 0) * line.quantity)}`).join("\n");
  const messengerUrl = `https://m.me/61593084964524?text=${encodeURIComponent(`Hello VANGUARD, I would like to inquire about:\n\n${summary}\n\nEstimated total: ${formatPeso(total)}`)}`;
  if (!lines.length) return <section className="mx-auto max-w-3xl px-4 py-24 text-center"><h1 className="font-serif text-5xl font-semibold text-emerald">Your cart is empty</h1><p className="mt-4 text-sm text-emerald/65">Explore the VANGUARD collection and add products for your inquiry.</p><Link href="/shop" className="mt-8 inline-flex bg-emerald px-7 py-4 text-xs uppercase tracking-[0.15em] text-ivory">Continue Shopping</Link></section>;
  return <section className="mx-auto max-w-5xl px-4 py-12 sm:px-8 lg:py-16"><div className="text-center"><p className="text-[10px] uppercase tracking-[0.24em] text-gold">Your selection</p><h1 className="mt-2 font-serif text-5xl font-semibold text-emerald">Shopping Cart</h1></div><div className="mt-10 divide-y divide-emerald/10 border-y border-emerald/10">{lines.map(({ product, quantity }) => product && <article key={product.slug} className="grid grid-cols-[80px_1fr] gap-4 py-5 sm:grid-cols-[110px_1fr_auto] sm:items-center"><div className="group relative aspect-square overflow-hidden rounded-lg bg-[#f4efe4]"><ProductImage product={product} /></div><div><Link href={`/shop/${product.slug}`} className="font-serif text-xl font-semibold text-emerald">{product.name}</Link><p className="mt-1 text-xs text-gold">{product.category}</p><p className="mt-2 text-sm font-semibold text-emerald">{formatPeso(product.price)}</p><div className="mt-3 flex items-center gap-3"><button type="button" aria-label={`Decrease ${product.name} quantity`} onClick={() => updateQuantity(product.slug, quantity - 1)} className="h-8 w-8 border border-emerald/20">−</button><span className="min-w-4 text-center text-sm">{quantity}</span><button type="button" aria-label={`Increase ${product.name} quantity`} onClick={() => updateQuantity(product.slug, quantity + 1)} className="h-8 w-8 border border-emerald/20">+</button><button type="button" onClick={() => removeFromCart(product.slug)} className="ml-2 text-[10px] uppercase tracking-wider text-emerald/55 underline">Remove</button></div></div><p className="col-start-2 text-right font-semibold text-emerald sm:col-auto">{formatPeso(product.price * quantity)}</p></article>)}</div><div className="ml-auto mt-8 max-w-md bg-white/55 p-6"><div className="flex items-center justify-between"><span className="text-xs uppercase tracking-[0.14em] text-emerald/60">Estimated total</span><strong className="font-serif text-3xl text-emerald">{formatPeso(total)}</strong></div><p className="mt-4 text-xs leading-5 text-emerald/60">Orders are finalized directly with VANGUARD. No online payment will be collected.</p><a href={messengerUrl} target="_blank" rel="noreferrer" className="mt-6 flex h-12 items-center justify-center bg-gold px-5 text-center text-xs uppercase tracking-[0.14em] text-emerald">Inquire via Messenger</a><a href={`mailto:${site.email}?subject=VANGUARD Product Inquiry&body=${encodeURIComponent(`${summary}\n\nEstimated total: ${formatPeso(total)}`)}`} className="mt-3 flex h-12 items-center justify-center border border-emerald text-xs uppercase tracking-[0.14em] text-emerald">Send Email Inquiry</a></div></section>;
}
